### ISSUE TITLE
Doesn't work without suggested package CVXR

### ISSUE THREAD

**Issue by Enchufa2** [dppalomar/spectralGraphTopology#9]
#### Problem description
Package is declared in Suggests, but it is used on package load. As a result, it doesn't work on systems without CVXR.

#### Example
See the [build log](https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-37-x86_64/04853884-R-CRAN-spectralGraphTopology/builder-live.log.gz):

```
** R
** inst
** byte-compile and prepare package for lazy loading
Error in library(CVXR) : there is no package called 'CVXR'
Error: unable to load R code in package 'spectralGraphTopology'
Execution halted
ERROR: lazy loading failed for package 'spectralGraphTopology'
* removing '/builddir/build/BUILDROOT/R-CRAN-spectralGraphTopology-0.2.3-1.fc37.copr4853884.x86_64/usr/local/lib/R/library/spectralGraphTopology'
error: Bad exit status from /var/tmp/rpm-tmp.gMNrVw (%install)
```

#### Expected behavior
The package should work without CVXR, or CVXR should be promoted to Imports or Depends.

#### Environment:
- platform (e.g. Linux, OSX, Windows): Linux
- spectralGraphTopology version (e.g. 0.2): 0.2.3
- installation method (e.g. CRAN, source): source

**Comment by mirca** [comment]
Thanks! This has been fixed in [d8af461].(https://github.com/dppalomar/spectralGraphTopology/commit/d8af461a4cd7054867e040d24f9ffa4c67bd8af6)
